List<String> categories = [
  "Children and Youth",
  "Educational",
  "Environmental",
  "Healthcare",
  "Animal welfare",
  "Disaster Relief",
  "Human Rights",
  "Senior Care",
];

List<Map<String, dynamic>> volunteeringEvents = [
  {
    'title': 'Back to School Drive',
    'category': 'Children and Youth',
    'description':
        'Help us collect and distribute school supplies for underprivileged children in the community.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 100,
    'slotsLeft': 50,
    'organizationName': 'The Happy Child Foundation',
  },
  {
    'title': 'Mentorship Program',
    'category': 'Children and Youth',
    'description':
        'Join us in mentoring and guiding at-risk youth in the community towards a brighter future.',
    'organizationType': 'Community-based organization',
    'volunteersNeeded': 50,
    'slotsLeft': 20,
    'organizationName': 'The Youth Empowerment Project',
  },
  {
    'title': 'Eco-Friendly Cleanup',
    'category': 'Environmental',
    'description':
        'Join us in cleaning up the local park and promoting eco-friendly habits in the community.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 200,
    'slotsLeft': 100,
    'organizationName': 'Green Earth Alliance',
  },
  {
    'title': 'Tree Planting Event',
    'category': 'Environmental',
    'description':
        'Help us plant trees in the community and combat climate change.',
    'organizationType': 'Community-based organization',
    'volunteersNeeded': 100,
    'slotsLeft': 30,
    'organizationName': 'The Tree Huggers Association',
  },
  {
    'title': 'Blood Drive',
    'category': 'Healthcare',
    'description': 'Donate blood and help save lives in the community.',
    'organizationType': 'Hospital',
    'volunteersNeeded': 50,
    'slotsLeft': 10,
    'organizationName': 'Saint Mary Hospital',
  },
  {
    'title': 'Fitness and Nutrition Workshop',
    'category': 'Healthcare',
    'description':
        'Join us in promoting healthy habits and lifestyles in the community.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 30,
    'slotsLeft': 5,
    'organizationName': 'The Health and Wellness Initiative',
  },
  {
    'title': 'Pet Adoption Drive',
    'category': 'Animal welfare',
    'description':
        'Help us find forever homes for abandoned pets in the community.',
    'organizationType': 'Animal shelter',
    'volunteersNeeded': 20,
    'slotsLeft': 10,
    'organizationName': 'The Furry Friends Rescue',
  },
  {
    'title': 'Dog Walking Event',
    'category': 'Animal welfare',
    'description':
        'Join us in walking dogs and promoting animal welfare in the community.',
    'organizationType': 'Community-based organization',
    'volunteersNeeded': 10,
    'slotsLeft': 2,
    'organizationName': 'The Pawsitive Movement',
  },
  {
    'title': 'Disaster Relief Fundraiser',
    'category': 'Disaster Relief',
    'description':
        'Help us raise funds to support disaster relief efforts around the world.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 100,
    'slotsLeft': 50,
    'organizationName': 'The Disaster Relief Foundation',
  },
  {
    'title': 'Emergency Preparedness Workshop',
    'category': 'Disaster Relief',
    'description':
        'Join us in educating the community on emergency preparedness and response in the event of a disaster.',
    'organizationType': 'Community-based organization',
    'volunteersNeeded': 30,
    'slotsLeft': 15,
    'organizationName': 'The Emergency Response Team',
  },
  {
    'title': 'Human Rights Advocacy Campaign',
    'category': 'Human Rights',
    'description':
        'Join us in advocating for human rights and raising awareness on social justice issues in the community.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 50,
    'slotsLeft': 20,
    'organizationName': 'The Social Justice Movement',
  },
  {
    'title': 'Refugee Support Drive',
    'category': 'Human Rights',
    'description':
        'Help us collect and distribute supplies for refugees in the community.',
    'organizationType': 'Community-based organization',
    'volunteersNeeded': 20,
    'slotsLeft': 5,
    'organizationName': 'The Refugee Support Network',
  },
  {
    'title': 'Senior Care Companion Program',
    'category': 'Senior Care',
    'description':
        'Join us in providing companionship and support to seniors in the community.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 30,
    'slotsLeft': 10,
    'organizationName': 'The Elderly Care Association',
  },
  {
    'title': 'Meals on Wheels Delivery',
    'category': 'Senior Care',
    'description':
        'Help us deliver meals to homebound seniors in the community.',
    'organizationType': 'Community-based organization',
    'volunteersNeeded': 10,
    'slotsLeft': 2,
    'organizationName': 'The Meals on Wheels Program',
  },
  {
    'title': 'Youth Mentorship Program',
    'category': 'Children and Youth',
    'description':
        'Join us in mentoring and guiding at-risk youth in the community.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 20,
    'slotsLeft': 5,
    'organizationName': 'The Youth Empowerment Organization',
  },
  {
    'title': 'Green Space Restoration Project',
    'category': 'Environmental',
    'description':
        'Help us restore and maintain local green spaces for the community to enjoy.',
    'organizationType': 'Community-based organization',
    'volunteersNeeded': 40,
    'slotsLeft': 10,
    'organizationName': 'The Green Space Restoration Initiative',
  },
  {
    'title': 'Free Health Clinic',
    'category': 'Healthcare',
    'description':
        'Join us in providing free healthcare services to underserved communities.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 100,
    'slotsLeft': 50,
    'organizationName': 'The Health for All Initiative',
  },
  {
    'title': 'Pet Adoption Drive',
    'category': 'Animal Welfare',
    'description':
        'Help us find forever homes for animals in need by volunteering at our pet adoption event.',
    'organizationType': 'Community-based organization',
    'volunteersNeeded': 15,
    'slotsLeft': 3,
    'organizationName': 'The Animal Adoption Network',
  },
  {
    'title': 'Disaster Relief Fundraiser',
    'category': 'Disaster Relief',
    'description':
        'Help us raise funds for disaster relief efforts in communities affected by natural disasters.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 30,
    'slotsLeft': 10,
    'organizationName': 'The Disaster Relief Fund',
  },
  {
    'title': 'Social Services Volunteer',
    'category': 'Human Rights',
    'description':
        'Join us in providing support and assistance to individuals and families in need of social services.',
    'organizationType': 'Community-based organization',
    'volunteersNeeded': 25,
    'slotsLeft': 5,
    'organizationName': 'The Social Services Network',
  },
  {
    'title': 'Elderly Community Center Volunteer',
    'category': 'Senior Care',
    'description':
        'Join us in volunteering at a local community center for elderly individuals, providing companionship and assistance.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 15,
    'slotsLeft': 2,
    'organizationName': 'The Elderly Community Center',
  },
  {
    'title': 'Youth Tutoring Program',
    'category': 'Children and Youth',
    'description':
        'Help us provide academic support and mentorship to young students from low-income families.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 30,
    'slotsLeft': 8,
    'organizationName': 'The Academic Mentorship Initiative',
  },
  {
    'title': 'Eco-Friendly Lifestyle Workshop',
    'category': 'Environmental',
    'description':
        'Join us in educating the community about sustainable living practices and reducing their carbon footprint.',
    'organizationType': 'Community-based organization',
    'volunteersNeeded': 20,
    'slotsLeft': 5,
    'organizationName': 'The Eco-Lifestyle Project',
  },
  {
    'title': 'Medical Outreach Program',
    'category': 'Healthcare',
    'description':
        'Volunteer with us to provide medical care and resources to underserved communities around the world.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 50,
    'slotsLeft': 20,
    'organizationName': 'The Global Medical Outreach Program',
  },
  {
    'title': 'Wildlife Conservation Expedition',
    'category': 'Animal Welfare',
    'description':
        'Join us on a conservation expedition to protect endangered species and their habitats.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 10,
    'slotsLeft': 2,
    'organizationName': 'The Wildlife Conservation Society',
  },
  {
    'title': 'Emergency Response Team Training',
    'category': 'Disaster Relief',
    'description':
        'Volunteer with us to be trained in emergency response procedures and help communities during times of crisis.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 15,
    'slotsLeft': 5,
    'organizationName': 'The Emergency Response Training Initiative',
  },
  {
    'title': 'Immigrant Rights Advocacy',
    'category': 'Human Rights',
    'description':
        'Join us in advocating for the rights and safety of immigrants and refugees in our community.',
    'organizationType': 'Community-based organization',
    'volunteersNeeded': 25,
    'slotsLeft': 10,
    'organizationName': 'The Immigrant Rights Coalition',
  },
  {
    'title': 'Meals on Wheels Delivery',
    'category': 'Senior Care',
    'description':
        'Volunteer with us to deliver meals to homebound seniors and provide them with companionship.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 20,
    'slotsLeft': 3,
    'organizationName': 'The Meals on Wheels Foundation',
  },
   {
    'title': 'STEM Education Volunteer',
    'category': 'Educational',
    'description': 'Join us in teaching STEM subjects to students in underserved communities.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 10,
    'slotsLeft': 2,
    'organizationName': 'The STEM Education Initiative',
  },
  {
    'title': 'Beach Cleanup Event',
    'category': 'Environmental',
    'description': 'Help us keep our beaches clean by volunteering at our beach cleanup event.',
    'organizationType': 'Community-based organization',
    'volunteersNeeded': 30,
    'slotsLeft': 5,
    'organizationName': 'The Beach Cleanup Project',
  },
  {
    'title': 'Food Bank Volunteer',
    'category': 'Healthcare',
    'description': 'Join us in providing food assistance to families in need at our local food bank.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 20,
    'slotsLeft': 10,
    'organizationName': 'The Food Bank Network',
  },
  {
    'title': 'Pet Therapy Program',
    'category': 'Animal Welfare',
    'description': 'Join us in bringing joy and comfort to individuals in need through pet therapy visits.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 15,
    'slotsLeft': 3,
    'organizationName': 'The Pet Therapy Program',
  },
  {
    'title': 'Emergency Preparedness Training',
    'category': 'Disaster Relief',
    'description': 'Learn how to prepare and respond to emergencies in your community by volunteering at our emergency preparedness training.',
    'organizationType': 'Community-based organization',
    'volunteersNeeded': 50,
    'slotsLeft': 20,
    'organizationName': 'The Emergency Preparedness Network',
  },
  {
    'title': 'Immigrant Rights Volunteer',
    'category': 'Human Rights',
    'description': 'Join us in advocating for immigrant rights and providing assistance to immigrant communities.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 10,
    'slotsLeft': 2,
    'organizationName': 'The Immigrant Rights Advocacy Group',
  },
  {
    'title': 'Meals on Wheels Volunteer',
    'category': 'Senior Care',
    'description': 'Join us in delivering meals and providing companionship to homebound elderly individuals in our community.',
    'organizationType': 'Non-profit',
    'volunteersNeeded': 30,
    'slotsLeft': 5,
    'organizationName': 'The Meals on Wheels Program',
  },
];
